models/table.py
import os
from dotenv import  load_dotenv
from peewee import MySQLDatabase, Model, CharField, DateTimeField
import datetime

load_dotenv()
db = MySQLDatabase(
    host = os.getenv("host"),
    user = os.getenv("user"),
    password = os.getenv("password"),
    database = os.getenv("database"),
    port = int(os.getenv("port"))
)

class Cliente(Model):
    Nome = CharField()
    Email = CharField()
    data_registro = DateTimeField(default=datetime.datetime.now())

    class Meta:
        database = db

main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route
from models.table import db, Cliente

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix="/clientes")

if __name__ == "__main__":
    db.connect()
    db.create_tables([ Cliente ])
    app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from models.table import db, Cliente

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route("/")
def lista_cliente():

    clientes = Cliente.select()
    return render_template("listar_clientes.html", clientes = clientes)

@cliente_route.route("/new")
def form_cliente():
    # formulário para inserir novo cliente
    return render_template("form.html")

@cliente_route.route("/", methods=["POST"])
def inserir_cliente():

    data = request.json
    
    novo_usuario = Cliente.create(
        Nome = data["nome"], 
        Email = data["email"]
        )
    
    return render_template("item_cliente.html", cliente=novo_usuario)

@cliente_route.route("/<int:cliente_id>/exibir")
def detalhe_cliente(cliente_id):

    cliente = Cliente.get_by_id(cliente_id)
    return render_template("detalhe_cliente.html", cliente=cliente)

@cliente_route.route("/<int:cliente_id>/delete", methods=["DELETE"])
def deletar_cliente(cliente_id):

    cliente = Cliente.get_by_id(cliente_id)
    cliente.delete_instance()
    return {"DELETAR": "OK"}


@cliente_route.route("/<int:cliente_id>/edit")
def form_edit_cliente(cliente_id):

    cliente = Cliente.get_by_id(cliente_id)
    return render_template("form.html", cliente=cliente)

@cliente_route.route("/<int:cliente_id>/update", methods=["PUT"])
def editar_cliente(cliente_id):
    """ atualizar informacoes do cliente """
    cliente_editado = None

    # obter dados do formulario de edicao
    data = request.json

    # obter usuario pelo id
    cliente_editado = Cliente.get_by_id(cliente_id)
    cliente_editado.Nome = data["nome"]
    cliente_editado.Email = data["email"]
    cliente_editado.save()
            
    return render_template("item_cliente.html", cliente = cliente_editado)

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route("/")
def index():
    return render_template("index.html")

templates/detalhe_cliente.html
<ul>
    <li>id: {{cliente.id}}</li>
    <li>Nome: {{cliente.Nome}}</li>
    <li>Email: {{cliente.Email}}</li>
</ul>

templates/form.html
<form class="c-form" 
        {% if cliente %}
            action="{{ url_for('cliente.editar_cliente', cliente_id = cliente.id) }}" 
        {% else %}
            action="{{ url_for('cliente.inserir_cliente') }}" 
        {% endif %}

        method="{% if cliente %}PUT{% else %}POST{% endif %}"
            
        {% if cliente %}
            c-swap="#cliente-{{cliente.id}}"
        {% else%}
            c-append="#lista_cliente"
        {% endif %}

        c-reload-container="true"
        >
        
    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="text" class="form-control" name="nome"
        {% if cliente %} value="{{ cliente.Nome }}"{% endif %}> 
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" name="email"
        {% if cliente %} value="{{ cliente.Email }}" {% endif %}>
    </div>
    <button type="submit" class="btn btn-primary">
        {% if cliente %} Atualizar Cliente {% else %} Adicionar Cliente {% endif %}
    </button>
</form>

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Testando Bootstrap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Gestão de Clientes</h1>

        <!--ADD cliente-->
        <div id="form_cliente" c-container="{{ url_for( 'cliente.form_cliente') }}""></div>

        <!--Lista de clientes-->
        <div c-container=" {{ url_for('cliente.lista_cliente') }}"></div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="exibir_cliente"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="{{ url_for( 'static', filename='js/crud.js' )}}"></script>
</body>

</html>

templates/item_cliente.html
<tr id="cliente-{{cliente.id}}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.Nome }}</td>
    <td>{{ cliente.Email }}</td>
    <td>
        <button class="btn btn-secondary"
        c-get="{{ url_for('cliente.detalhe_cliente', cliente_id = cliente.id) }}"
        c-target="#exibir_cliente"
        data-bs-toggle="modal" data-bs-target="#exampleModal">
            Ver
        </button>

        <button class="btn btn-primary"
        c-get="{{ url_for('cliente.form_edit_cliente', cliente_id = cliente.id) }}"
        c-target="#form_cliente">
            Editar
        </button>

        <button class="btn btn-danger"
        c-delete="{{ url_for('cliente.deletar_cliente', cliente_id = cliente.id) }}"
        c-remove-closest="tr">
            Excluir
        </button>
    </td>
</tr>

templates/listar_clientes.html
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody id="lista_cliente">
    {% for cliente in clientes %}
        {% include 'item_cliente.html' %}
    {% endfor%}
    </tbody>
</table>